#!/usr/bin/env bun

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const promptsDir = join("harnesses", "code-review", "prompts");
const outputPath = join("harnesses", "code-review", "src", "embedded-prompts.ts");

function toRoleId(fileName: string): string {
  return fileName.replace(/\.md$/i, "");
}

async function main(): Promise<void> {
  const entries = await readdir(promptsDir);
  const promptFiles = entries
    .filter((entry) => entry.toLowerCase().endsWith(".md"))
    .sort((left, right) => left.localeCompare(right));

  const prompts: Record<string, string> = {};
  for (const fileName of promptFiles) {
    const roleId = toRoleId(fileName);
    const content = await readFile(join(promptsDir, fileName), "utf8");
    prompts[roleId] = content;
  }

  const generated = `${[
    "// Auto-generated by scripts/embed-prompts.ts. Do not edit manually.",
    "",
    "export const EMBEDDED_PROMPTS: Readonly<Record<string, string>> =",
    `${JSON.stringify(prompts, null, 2)};`,
    "",
  ].join("\n")}`;

  await writeFile(outputPath, generated, "utf8");
  process.stdout.write(`Embedded ${promptFiles.length} prompts into ${outputPath}\n`);
}

await main();
